package: theme_lock
version: '1.0.0'
author: 'FriendsOfREDAXO'
supportpage: https://github.com/FriendsOfREDAXO/theme_lock
load: early
requires:
    redaxo: '^5.13.0'
    php:
        version: '>=7.3, <9'
